BecasCep/Controllers/AdminController.cs
using BecasCep.Models;
using BecasCep.Models.Dominio;
using BecasCep.Models.Enums;
using BecasCep.Models.ViewModels.Persona;
using BecasCep.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BecasCep.Controllers
{
    //[Authorize (Roles = RoleConst.Administrador)]
    public class AdminController : Controller
    {
        private ApplicationDbContext db;

        public AdminController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Admin
        public ActionResult ListadoAdmin()
        {
            var repoPersona = new Repositorio<Persona>(db);
            var personas = repoPersona.TraerTodos().Where(p => !p.Eliminado).OrderBy(p => p.Nombre).ToList().Select(p => new PersonaIndexViewModel()
            {
                Id = p.Id,
                Nombre = p.Nombre,
                Apellido = p.Apellido,
                Dni = p.Dni,
                Email = p.Email,
                Telefono = p.Telefono,
                Estado = p.Estado,
                Carrera = new Models.ViewModels.Carrera.CarreraViewModel()
                {
                    Nombre = p.Carrera.Nombre,
                    Sede = p.Carrera.Sede,
                    Turno = p.Carrera.Turno
                    
                }
            }).ToList();
            return View(personas);
        }

        public JsonResult Eliminar(Guid id)
        {
            var repoPersona = new Repositorio<Persona>(db);
            repoPersona.Eliminar(repoPersona.Traer(id));
            return Json("ok", JsonRequestBehavior.AllowGet);
        }

        public JsonResult CambiarEstado(bool estado, Guid id)
        {
            var repoPersona = new Repositorio<Persona>(db);
            var persona = repoPersona.Traer(id);
            persona.Estado = estado;
            repoPersona.Modificar(persona);
            return Json("ok", JsonRequestBehavior.AllowGet);
        }
    }
}

BecasCep/Controllers/InscripcionController.cs
using BecasCep.Models;
using BecasCep.Models.Dominio;
using BecasCep.Models.Enums;
using BecasCep.Models.ViewModels.Persona;
using BecasCep.Repositorio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BecasCep.Controllers
{
    public class InscripcionController : Controller
    {
        private ApplicationDbContext db;
        // GET: Inscripcion
        public InscripcionController()
        {
            db = new ApplicationDbContext();
        }
        public ActionResult Listado()
        {
            var repoPersona = new Repositorio<Persona>(db);
            var personas = repoPersona.TraerTodos().Where(p => !p.Eliminado && !p.Sorteado).ToList().Select(p => new PersonaIndexViewModel()
            {
                Nombre = p.Nombre,
                Apellido = p.Apellido,
                Dni = p.Dni,
                Email = p.Email,
                Telefono = p.Telefono,
                Carrera = new Models.ViewModels.Carrera.CarreraViewModel()
                {
                    Nombre = p.Carrera.Nombre,
                    Sede = p.Carrera.Sede,
                    Turno = p.Carrera.Turno
                }
            }).ToList();
            return View(personas);
        }

        public ActionResult ListadoGanadores()
        {
            var repoPersona = new Repositorio<Persona>(db);
            var personas = repoPersona.TraerTodos().Where(p => !p.Eliminado && p.Sorteado).ToList().Select(p => new PersonaIndexViewModel()
            {
                Nombre = p.Nombre,
                Apellido = p.Apellido,
                Dni = p.Dni,
                Email = p.Email,
                Telefono = p.Telefono,
                Carrera = new Models.ViewModels.Carrera.CarreraViewModel()
                {
                    Nombre = p.Carrera.Nombre,
                    Sede = p.Carrera.Sede,
                    Turno = p.Carrera.Turno
                }
            }).ToList();
            return View(personas);
        }

        public void CrearPersonasTest()
        {
            var repoPersona = new Repositorio<Persona>(db);
            Persona persona = null;
            for (int i = 0; i < 300; i++)
            {
                persona = new Persona()
                {
                    Nombre = "Nombre" + i,
                    Apellido = "Apellido" + i,
                    Dni = new Random().Next(0, 30333333).ToString(),
                    Email = "test" + i + "@test.com",
                    Telefono = new Random().Next(0, 30333333).ToString(),
                    Estado = false,
                    Sorteado = false,
                    Carrera = new Carrera()
                    {
                        Nombre = Enum.GetNames(typeof(TipoCarrera)).ToList().ElementAt(new Random().Next(0, 2)),
                        Sede = (Sede)Enum.Parse(typeof(Sede), Enum.GetNames(typeof(Sede)).ToList().ElementAt(new Random().Next(0, 2))),
                        Turno = (Turno)Enum.Parse(typeof(Turno), Enum.GetNames(typeof(Turno)).ToList().ElementAt(new Random().Next(0, 3))),
                    }
                };
                repoPersona.Crear(persona);
            }
        }

        public ActionResult Crear()
        {
            PersonaViewModel model = new PersonaViewModel();
            return View(model);
        }

        [HttpPost]
        public ActionResult Crear(PersonaViewModel model)
        {
            if (ModelState.IsValid)
            {
                Persona persona = new Persona(model);
                var repoPersona = new Repositorio<Persona>(db);
                repoPersona.Crear(persona);
                return RedirectToAction("Listado");
            }
            return View(model);

        }


        [AllowAnonymous]
        [HttpPost]
        public ActionResult DniRepetido(string dni)
        {
            var repoPersonas = new Repositorio<Persona>(db);
            return Json(!repoPersonas.TraerTodos().Where(p => !p.Eliminado).Any(a =>a.Dni == dni));
        }





    }
}

BecasCep/Views/Shared/_Layout.cshtml
@{
    string url = HttpContext.Current.Request.Url.AbsolutePath;
}

<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap core CSS -->
    <link href="~/Content/css/jquery.dataTables.min.css" rel="stylesheet" />

    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom fonts for this template -->

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="~/Content/agency.min.css" rel="stylesheet" />
    <link href="~/fonts/font-awesome.min.css" rel="stylesheet" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />

        <link href="~/Content/Site.css" rel="stylesheet" />
        <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />



        <link href="~/Content/agency.min.css" rel="stylesheet" />


        <link href="~/Content/animation.css" rel="stylesheet" />
        <link href="~/Content/css/main.css" rel="stylesheet" />
        <link href="~/Content/css/util.css" rel="stylesheet" />
        <link href="~/Content/perfect-scrollbar.css" rel="stylesheet" />
        <link href="~/Content/bootstrap-reboot.min.css" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700"
              rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Kaushan+Script'
              rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic'
              rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700'
              rel='stylesheet' type='text/css'>*@
    @*<link type="text/css" rel="stylesheet" hrf="https://cdnjs.cloudflare.com/ajax/libs/jquery-bootgrid/1.3.1/jquery.bootgrid.css" />*@


</head>
<body id="page-top">
    <header class="masthead" id="image">
        <div class="container">
            <div class="intro-text">
                <div class="intro-heading text-uppercase" style="font-size: 5vw;">
                    Becas
                    de apuntes y fotocopiadora del CEP
                </div>
                <div class="intro-lead-in"></div>
                <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger"
                   href="#encuesta" style="visibility: hidden;">Becas de apuntes</a>
            </div>
        </div>
    </header>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">Becas Cep</a><i></i>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav text-uppercase ml-auto">
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" Href="@Url.Action("Crear","Inscripcion")">Inscribisrse</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" Href="@Url.Action("ListadoGanadores","Inscripcion")">Ganadores</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" Href="@Url.Action("Listado","Inscripcion")">Listado Inscriptos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link js-scroll-trigger" Href="@Url.Action("Login","Account")">Login</a>
                    </li>
                    @if (Request.IsAuthenticated && User.IsInRole(BecasCep.Models.Enums.RoleConst.Administrador))
                    {
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" Href="@Url.Action("Sorteo","Sorteo")">Sorteo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" Href="@Url.Action("ListadoAdmin","Admin")">Listado Admin</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link js-scroll-trigger" Href="@Url.Action("LogOff","Account")">Logout</a>
                        </li>
                    }

                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">

        @RenderBody()

        <hr />
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <span class="copyright">Copyright &copy; pablopodgaiz 2018</span>
                    </div>
                    <div class="col-md-4">
                        <ul class="list-inline social-buttons">

                            <li class="list-inline-item">
                                <a href="https://www.facebook.com/CEP.UBA/">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="https://www.instagram.com/impulso_nuevocep/">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </footer>
    </div>



    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Contact form JavaScript -->




    <script src="~/Scripts/contact_me.min.js"></script>
    <!-- Custom scripts for this template -->

    <script src="~/Scripts/agency.min.js"></script>

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>

    <script src="~/Scripts/jquery-3.3.1.intellisense.js"></script>

    <script src="~/Scripts/SweetAlert.Js"></script>
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jqBootstrapValidation.js"></script>
    <script src="~/Scripts/jquery.easing.min.js"></script>
    @*

        <script src="~/Scripts/jquery-3.3.1.slim.min.js"></script>


        <script src="~/Scripts/bootstrap.bundle.min.js"></script>

        <script src="~/Scripts/jquery.easing.min.js"></script>


        <script src="~/Scripts/jquery.easing.compatibility.js"></script>

        <script src="~/Scripts/datatables.extensions/TableTools/js/dataTables.tableTools.js"></script>
        <script src="~/Scripts/contact_me.min.js"></script>
        <script src="~/Scripts/jquery.validate.min.js"></script>
        <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/Scripts/modernizr-2.8.3.js"></script>

        <script src="~/Scripts/perfect-scrollbar.min.js"></script>*@

</body>
</html>
@RenderSection("scripts", false)